# Hoja 3
## Carlos Farouk Abdala
## Tomas Candelo 
## Gabriel Jimenez 

In [6]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

## Exercise 1
### Exercise 1.1

In [7]:
# matrix without function

D = np.array([[10, 12], [7, 8], [5, 4]])
D_covariance = np.cov(D, rowvar=False, bias=True)
eigenvalues, eigenvectors = np.linalg.eig(D_covariance)
print("eigenvalues of D_covariance \n", eigenvalues, "\n")
print("eigenvectors of D_covariance \n", eigenvectors, "\n")

# matrix with function
def transformation (x):
    return 2*x + 5
function = np.vectorize(transformation)
trans_D = function(D)    
trans_D_covariance = np.cov(trans_D, rowvar=False, bias=True)
eigenvalues_trans, eigenvectors_trnas = np.linalg.eig(trans_D_covariance)
print("eigenvalues of trans_D_covariance \n", eigenvalues_trans, "\n")
print("eigenvectors of trans_D_covariance \n", eigenvectors_trnas)

eigenvalues of D_covariance 
 [ 0.03990796 14.84898093] 

eigenvectors of D_covariance 
 [[-0.84710349 -0.53142795]
 [ 0.53142795 -0.84710349]] 

eigenvalues of trans_D_covariance 
 [ 0.15963186 59.3959237 ] 

eigenvectors of trans_D_covariance 
 [[-0.84710349 -0.53142795]
 [ 0.53142795 -0.84710349]]


### Exercise 1.2

En este caso buscamos demostrar que los componentes principales, vectores propios de la matriz de correlación, es igual en la matriz original y la matriz transformada por una función afin, primero decleremos los siguientes valores:
D ------> La matriz sin transformar  
DTrans -------> La matriz tranformada por una transformación  
covarianza --------> matriz de covarianza de D  
covarianza_transformada --------> matriz de covarianza de DT  
vector propio ------> vectores propios de la matriz de correlación  

Una vez definido esto es necesario centrar los datos de la matriz para obtener la covarianza de esta la cual esta definida por la siguiente ecuación
$$ ecuación 1: covarianzaTranformada = \frac{1}{n} \sum_{i=1}^{n} (D_centradoT * D_centrado) $$
Donde D_centradoT son los datos centralizados transpuestos y D_centrado son los datos centrados normales y se expresan como 
$$ euación 2: D_centrado = D - media $$

Esta ecuación de la covarianza la vamos a asemejar como la de correlación ya que estas dos matrices son semejantes en este caso  

De la hoja anterior podemos de igual manera decir que la media transformada esta determinada por la siguiente ecuación
$$ ecuación 3: media-tranfrormada = a*media + b $$

Entonces si aplicamos la matriz transformada a la ecuación 1 y los valores centrados los cambiamos por la ecuación 2 tendriamos que
$$  Correlación-Transformada = \frac{1}{n} * (DTtrans - mediaTransformadaT)T * (DT - mediaTransformadaT) $$

Ahora si cambiamos los valores de la ecuacíon por la formula que equivale su tranformación seria

$$  \frac{1}{n} * (a*D + b - a*media + b)T * (a*D + b - a*media + b) $$

simplificamos y obtenemos 

$$  \frac{1}{n} * DT*AT*AD - \frac{1}{n} * DT*AT*A*media - \frac{1}{n} mediaT * AT * AD - \frac{1}{n} mediaT*AT * A*media $$ 

Dado que A es una matriz de valores escalares A*AT tambien es una matriz escalar y ya que la definición dada en la hoja nos dice que la matriz de covarianza y correlación son iguales porque sus valores son igual a 1 la expersión anterior puede ser simplificada a: 

$$  \frac{1}{n} * DT*D - \frac{1}{n} * DT*media - \frac{1}{n} mediaT*D - \frac{1}{n} mediaT*media $$

simplificando nuevamente obtenemos que 

$$  \frac{1}{n} * DT*D - mediaT * media$$

lo cual es semejante a decir que la correlación tranformada es igual a 1/n * Σ siendo sigma la matriz de covarianza original  

Si todo esto lo aplicamos a la formula Σ*v = α*v donde v son nuestros vectores propios y α es el valor propio, podemos concluir que la matriz de correlación, despues de transformarla, esta dada como una versión escalar de la matriz de covarianza original y las componentes principlaes (nuestros valores o vectores propios) estan relacionadas unicamente con la matriz de covarianza o de correlación, ya que estas son iguales entre si gracias a que sus varianzas equivalen a 1, por lo que estos componentes principales tampoco cambiaran, además cabe resaltar que α no cambia ni en la ecuación tranformada o sin tranformar, en otras palabras v'es el vector propio de la correlación de la matriz transformada que tiene como valor propio a α el cual es el mismo que tiene el vector propio v de la correlación de la matriz original


## Exercise 2
### Exercise 2.1

In [81]:
def PCA (D,red):
    u= np.array([])
    mean_of_D= np.mean(D)
    center_D= D-mean_of_D
    cov_D = np.cov(center_D, rowvar=False)

    eigenvalues, eigenvectors = np.linalg.eig(cov_D)
    eigenvalues= abs(eigenvalues)
    order_indices = np.argsort(eigenvalues)[::-1].tolist()

    sorted_eigenvalues = eigenvalues[order_indices]
    sorted_eigenvectors = eigenvectors[:, order_indices]
    total_variance=(np.sum(eigenvalues))
 
    if(0<=red and red<1):
        red_acum_variance=(total_variance*red)
        acum_variance=0
        r=0
        for index in range(len(sorted_eigenvalues)):
            r+=1
            acum_variance+=sorted_eigenvalues[index]
            if acum_variance > red_acum_variance:
                break
        if r!=0:
            u= sorted_eigenvectors[:,:r]
            D_resized = np.dot(center_D, u)
        else:
            return ("El valor de alpha solicitado es inválido para la matriz",0)
       
    if(red>=1 and int == type(red)):
        acum_variance= sum(sorted_eigenvalues[:red])
        u= sorted_eigenvectors[:,:red]
        D_resized = np.dot(center_D, u)

    ralative_variance= acum_variance/total_variance
    return (D_resized,acum_variance,ralative_variance)
 
 
xd=np.array([[4, 1, 0, 9, 8],
 [9, 9, 1, 6, 1],
 [4, 5, 3, 3, 5],
 [6, 2, 7, 3, 8],
 [5, 1, 0, 8, 1],
 [0, 4, 4, 6, 3],
 [3, 3, 7, 6, 3],
 [0, 6, 9, 3, 4],
 [4, 5, 0, 1, 6],
 [6, 5, 1, 3, 1]])
result_resized_matrix,x,y=PCA(xd,4)
print("Resized Matrix: \n",result_resized_matrix,"\n", x)

Resized Matrix: 
 [[-3.11273216  7.06900946 -0.71491566 -0.14481806]
 [-6.44017786 -4.31121635  0.81426174  2.10434123]
 [-0.33830938 -0.53906506 -1.4991341  -0.9863975 ]
 [ 2.79386745  1.81144522 -3.46468459  3.17354041]
 [-5.26390389  3.19697819  3.36861485 -0.10265341]
 [ 1.22025519  1.29206533  3.26998003 -2.47288453]
 [ 2.14174191  0.86500716  2.8457416   1.54720194]
 [ 6.03351134 -2.00536681  1.7907926  -0.81211878]
 [-1.93564975 -0.50696296 -3.95519963 -3.26488339]
 [-3.9875952  -2.3895917   0.25976856 -0.80591914]] 
 37.02020528711315


### Exercise 2.2

#### 2.2.a

In [55]:
# frames implementation
iris_frame_dowloaded = pd.read_csv("iris.csv")
filtered_iris_frame = iris_frame_dowloaded.loc[:, iris_frame_dowloaded.columns != "species"]
fabert_frame_dowloaded = pd.read_csv("fabert.csv")
filtered_fabert_frame = fabert_frame_dowloaded.drop(['class'],axis=1)
Amazon_frame_dowloaded = pd.read_csv("Amazon.csv")
filtered_Amazon_frame = Amazon_frame_dowloaded.loc[:, Amazon_frame_dowloaded.columns != "Class"]
baseball_numeric_frame_dowloaded = pd.read_csv("baseball_numeric.csv")

In [59]:
def getStats(A):
    n = len(A) 
    m = len(A[0]) 

    mean = [sum(col) / n for col in zip(*A)]

    central_A = [[A[i][j] - mean[j] for j in range(m)] for i in range(n)]
    central_A2=np.array(central_A)

    cov = np.dot(central_A2.T, central_A2) / n

    std_dev = np.sqrt(np.diag(cov))
    corr = [[cov[j][k] / (std_dev[j] * std_dev[k]) for k in range(m)] for j in range(m)]
    
    return mean, cov, corr


In [72]:
import time

data = {"dataset": ["iris", "fabert", "amazon", "baseball numeric"], "time with getStats": [], "time with corcoef": []}


datasets = [filtered_iris_frame, filtered_fabert_frame, filtered_Amazon_frame, baseball_numeric_frame_dowloaded]
for dataset in datasets:
    start1 = time.time()
    data_np = dataset.to_numpy()
    getStats(data_np)
    end1 = time.time()
    excecuting_time_with_getStats = end1 - start1
    start2 = time.time()
    corr2 = np.corrcoef(dataset, rowvar=False, bias=True)
    end2 = time.time()
    excecuting_time_with_corcoef = end2 - start2
    data["time with getStats"].append(excecuting_time_with_getStats)
    data["time with corcoef"].append(excecuting_time_with_corcoef)

data_frame = pd.DataFrame(data)
print(data_frame)


NameError: name 'getStats' is not defined

#### 2.2.b

In [83]:
red = 0.9
data = {"dataset": ["iris", "fabert", "amazon", "baseball numeric"], "requiere dimensions": [], "absolute variance": [], "relative variance": []}

datasets = [filtered_iris_frame, filtered_fabert_frame, filtered_Amazon_frame, baseball_numeric_frame_dowloaded]
for dataset in datasets:
    resized_matrix, variance,relative_variance = PCA(dataset, red)
    data["requiere dimensions"].append(len(resized_matrix[0]))
    data["absolute variance"].append(variance)
    data["relative variance"].append(relative_variance)
  
data_frame = pd.DataFrame(data)
print(data_frame)

4.22484076832011
2.5090248447354493
12155.426522811422
17228.15568572073
            dataset  requiere dimensions  absolute variance  relative variance
0              iris                    1           4.224841           0.924616
1            fabert                  516           2.509025           0.900382
2            amazon                  197       12155.426523           0.900145
3  baseball numeric                    2       17228.155686           0.989389
