***SHEET 5***


CARLOS FAROUK ABDALÁ RINCÓN

TOMAS CANDEO MONTOYA

GABRIEL DAVID JIMÉNEZ MOSQUERA

In [1]:
#IMPORTS
import numpy as np
import random
import math
import pandas as pd
import matplotlib.pyplot as plt
#import requests as rq
import itertools
from scipy.spatial.distance import pdist, squareform

C:\Users\CLILI\AppData\Local\Temp\ipykernel_18508\2499858933.py:5: DeprecationWarning: 
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466
        
  import pandas as pd


### EXERCISE 1

#### EXERCISE 1.1

In [5]:
import numpy as np
def getDistances(A):
    
    pairwise_distances = pdist(A, metric='euclidean')

    distance_matrix = squareform(pairwise_distances)
    
    return distance_matrix



A = np.array([[1], [2], [3]])
D = getDistances(A)
print(D)

[[0. 1. 2.]
 [1. 0. 1.]
 [2. 1. 0.]]
