***SHEET 2***


CARLOS FAROUK ABDALÁ RINCÓN

TOMAS CANDEO MONTOYA

GABRIEL DAVID JIMÉNEZ MOSQUERA

In [2]:
#IMPORTS
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

C:\Users\tomas\AppData\Local\Temp\ipykernel_24920\2844614886.py:3: DeprecationWarning: 
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466
        
  import pandas as pd


# EXERCISE 1

## EXERCISE 1.1

## EXERCISE 1.2

### 1.2.a

In [4]:
matrix = np.array([[92,80], [60, 30], [100, 70]])
mean_matrix = np.mean(matrix, axis=0)
central_matrix = matrix - mean_matrix
transpose_cental_matrix = central_matrix.T
dot_product = np.dot(transpose_cental_matrix, central_matrix)
covariance_matrix = dot_product / (matrix.shape[0])
print(covariance_matrix)

cov_matrix = np.cov(matrix, rowvar=False, bias=True)
print(cov_matrix)

[[298.66666667 346.66666667]
 [346.66666667 466.66666667]]
[[298.66666667 346.66666667]
 [346.66666667 466.66666667]]


In [5]:
# matrix without function

D = np.array([[10, 12], [7, 8], [5, 4]])
D_covariance = np.cov(D, rowvar=False, bias=True)
print("Covariation matrix without transformation \n", D_covariance)

# matrix with function
def transformation (x):
    return 6*x + 3
function = np.vectorize(transformation)
trans_D = function(D)    
trans_D_covariance = np.cov(trans_D, rowvar=False, bias=True)
print("\n Covariation of transformed matrix  \n", trans_D_covariance)

Covariation matrix without transformation 
 [[ 4.22222222  6.66666667]
 [ 6.66666667 10.66666667]]

 Covariation of transformed matrix  
 [[152. 240.]
 [240. 384.]]


### 1.2.b

In [6]:
#empirical mean

mean_D = np.mean(D, axis=0)
formula_for_D = transformation(mean_D)
print("\n Mean of D transformed by formula \n", formula_for_D)

mean_trans_D = np.mean(trans_D, axis=0)
print("\n Mean of D transformed by mean \n", mean_trans_D)

# empirical covariance
central_matrix_D = trans_D - formula_for_D
transpose_cental_matrix_D = central_matrix_D.T
dot_product_D = np.dot(transpose_cental_matrix_D, central_matrix_D)
covariance_matrix_D = dot_product_D / (D.shape[0])
print("\n Covariation matrix of transformed D by formula  \n", covariance_matrix_D)


trans_D_covariance_func = np.cov(trans_D, rowvar=False, bias=True)
print("\n Covariation matrix of transformed D by function  \n", trans_D_covariance_func)



 Mean of D transformed by formula 
 [47. 51.]

 Mean of D transformed by mean 
 [47. 51.]

 Covariation matrix of transformed D by formula  
 [[152. 240.]
 [240. 384.]]

 Covariation matrix of transformed D by function  
 [[152. 240.]
 [240. 384.]]


### 1.2.C

In [7]:
# Corelation in D
Corelation_D = np.corrcoef(D, rowvar=False)
print("\n Corelation in D \n", Corelation_D)

#corelation in transformed D
Corelation_D_trans = np.corrcoef(trans_D, rowvar=False)
print("\n Corelation in D transformed \n", Corelation_D_trans)


 Corelation in D 
 [[1.         0.99339927]
 [0.99339927 1.        ]]

 Corelation in D transformed 
 [[1.         0.99339927]
 [0.99339927 1.        ]]


la propiedad representa que las correlaciones de ambas matrices no cambian, esto ya que sin importar que en una se realizo una transformación afin, este tipo de transformaciones realiza una tranformación lineal y una traslación pero esto no afecta su comportamiento lineal por lo que este sera el mismo con este tipo de transformaciones

## Exercise 2.1


In [ ]:
## unit-tests for getStats and getEigen
import warnings
dfIrisTest = pd.read_csv("https://raw.githubusercontent.com/uiuc-cse/data-fa14/gh-pages/data/iris.csv")
AIris = dfIrisTest.values[:,0:4].astype(float)
def testStats(expected, A):
    out = getStats(A)
    if type(out) != tuple or len(out) != 3:
        warnings.warn("getStats not working properly! Output of getStats should be a tuple of length 3!")
        return
    mu, cov, cor = out
    print("mu:", "OK" if np.array_equal(np.round(expected[0], 3), np.round(mu, 3)) else "FAIL")
    print("cov:", "OK" if np.array_equal(np.round(expected[1], 3), np.round(cov, 3)) else "FAIL")
    print("cor:", "OK" if np.array_equal(np.round(expected[2], 3), np.round(cor, 3)) else "FAIL")

covIris = np.array([[ 0.681, -0.039, 1.265, 0.513], [-0.039, 0.187, -0.32, -0.117], [1.265, -0.32, 3.092, 1.288], [0.513, -0.117,  1.288,  0.579]])
testStats(([5.843, 3.054, 3.759, 1.199], covIris, np.array([[ 1., -0.109, 0.872, 0.818], [-0.109,  1., -0.421, -0.357], [0.872, -0.421, 1., 0.963], [0.818, -0.357, 0.963,  1.]])), AIris)

# Exercise 2.2

# Exercise 2.3